### PR TITLE
[WIP] Extract vec without specialization

### PR DESCRIPTION
**Pull request by davidhewitt**
Attempt to implement `FromPyObject` for `Vec<T>` with a buffer optimisation, *without* specialisation.

Can't merge because:

In this new design, `FromPyObject` for `Vec<String>` is not currently implemented, but `FromPyObject` for `String` is. In general this is a problem for all types which implement `FromPyObject` instead of `FromPyObjectImpl`.

Probably the solution is to make it ergonomic to implement `FromPyObjectImpl` directly for all types.

### CODE REVIEW

**Comment by davidhewitt** [comment]
I've come round to a design which is looking a lot cleaner. However, it still doesn't work for all types. The next step is probably to force implementations of `FromPyObjectImpl` rather than `FromPyObject` (by making `FromPyObject` have a `__private__` unimplementable method).

**Comment by kngwyu** [comment]
I haven't checked all implementation details... but do we really want to have some specific markers like `BufferElement` in general `FromPyObjectImpl`?

We use specialization here to use fast buffer protocol when it's applicable.
However, here's a problem...
Current `PyBuffer` is not really modified from `rust-cpython` era, and I feel it has really different semantics from other parts of PyO3.
`PyBuffer` is not compatible with `PyBufferProtocol` and `rust-numpy`.
It apparently needs overhauling.
So I don't want you to put too much effort around buffer protocol here...

**Comment by davidhewitt** [comment]
> do we really want to have some specific markers like BufferElement in general FromPyObjectImpl?

Not particularly, hi

**Comment by davidhewitt** [comment]
Another option I've considered: given this is just an optimisation, we could just disable this optimisation if compiling on stable Rust?

**Comment by davidhewitt** [comment]
(close and reopen was an accidental fat finger error)

**Comment by kngwyu** [comment]
> Another option I've considered: given this is just an optimisation, we could just disable this optimisation if compiling on stable Rust?

I think it's OK since I think rust-numpy is always better as *buffer*, though we can select some other choices...(e.g, implement `to_vec` for all types).
Anyway, we don't need to take it seriously now.

**Pull request closed without merging**
